### ISSUE TITLE
ChromeDriver example program

### ISSUE THREAD

**Issue by Programming4life** [jgraham/webdriver-rust#31]
Can someone give me a very simple sample program using the ChromeDriver that loads a page and finds an element with the id of "test-id"?
Thanks.

**Comment by Programming4life** [comment]
Are you guys able to help? @detro @SimonSapin

**Comment by jgraham** [comment]
As far as I know no one has implemented a WebDriver client based on this library so far; this is mostly a server implementation (although one could reuse many of the data structures to implement a client if one desired).
